### ISSUE TITLE
sometime can not save w3x!

### ISSUE THREAD

**Issue by qq1053831109** [inwc3/JMPQ3#41]
java.nio.BufferOverflowException
	at java.base/java.nio.DirectByteBuffer.put(DirectByteBuffer.java:410)
	at java.base/java.nio.ByteBuffer.put(ByteBuffer.java:906)
	at systems.crigges.jmpq3.MpqFile.writeFileAndBlock(MpqFile.java:348)
	at systems.crigges.jmpq3.MpqFile.writeFileAndBlock(MpqFile.java:277)
	at systems.crigges.jmpq3.JMpqEditor.close(JMpqEditor.java:799)
	at systems.crigges.jmpq3.JMpqEditor.close(JMpqEditor.java:705)
	at systems.crigges.jmpq3.JMpqEditor.close(JMpqEditor.java:701)

**Comment by Frotty** [comment]
Probably a jmpq issue, not wc3libs.
Needs reproducable example else can't do anything.

**Comment by qq1053831109** [comment]
yes i find the bug, if add file size in 1 - 7. then get the BufferOverflowException

**Comment by qq1053831109** [comment]
the one file content byte is 1 - 7

**Comment by Frotty** [comment]
Well, but why is it 1 - 7.

**Comment by qq1053831109** [comment]
i dont know . i just test get the number

**Comment by Frotty** [comment]
what's the map?
